### ISSUE TITLE
Unknown dependency: org.codehaus.groovy:groovy:2.5.6:indy

### ISSUE THREAD

**Issue by Sanne** [hibernate/query-validator#29]
The gradle build is referring to `org.codehaus.groovy:groovy:2.5.6:indy`, which I don't seem able to find.

The build seems to work if I replace this with `org.codehaus.groovy:groovy:2.5.6`, but I don't really know if that's fine.

**Comment by Sanne** [comment]
I mean it literally fails to build:

```
> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find groovy-indy.jar (org.codehaus.groovy:groovy:2.5.6).
     Searched in the following locations:
         file:/home/sanne/.m2/repository/org/codehaus/groovy/groovy/2.5.6/groovy-2.5.6-indy.jar

```

**Comment by gavinking** [comment]
Very strange.

It's right there in Maven central:

<https://repo1.maven.org/maven2/org/codehaus/groovy/groovy/2.5.6/>

And apparently that's where I got it from:

<img width="886" alt="Screen Shot 2020-02-27 at 13 49 08" src="https://user-images.githubusercontent.com/579974/75446593-fa0ed100-5967-11ea-9796-81c2e26f669d.png">

**Comment by Sanne** [comment]
That's the one without the '-indy' postfix.

Yes that one works for me too

**Comment by gavinking** [comment]
If I'm not mistaken `:indy` is a Maven classifier. It's saying we only want to use `groovy-2.5.6-indy.jar` instead of `groovy-2.5.6.jar`. They're both right there in Maven Central.

**Comment by Sanne** [comment]
ah yes sorry I hadn't noticed that your link showed the one with the `indy` qualifier as well.  Weird, at that same URL I don't see it.  Looks like a problem with the mirrors I have been using: by forcing a different mirror it builds just fine.

I'll close this then, thanks!
