### ISSUE TITLE
delete and update queries

### ISSUE THREAD

**Issue by gavinking** [hibernate/query-validator#32]
Apparently HQL `delete` queries don't work. (And `update` too, one supposes.)

**Comment by gavinking** [comment]
@FroMage I've tested some trivial examples, and they work for me so I need to know the precise example that breaks.

**Comment by gavinking** [comment]
Note to self: at minimum we need to add tests.

**Comment by FroMage** [comment]
Check out this branch: https://github.com/hibernate/query-validator/compare/master...FroMage:32?expand=1 to see the failure.

**Comment by FroMage** [comment]
Actually just adding the method and making it return `null` is enough to make the tests pass, so I'll do a PR at #36.
