### ISSUE TITLE
Want query-validator lib

### ISSUE THREAD

**Issue by mksolanki** [hibernate/query-validator#37]
Hello Gavin
I am looking for below dependency however it is not available on maven repo. Can you please give me jar file instead. Thank you very much.
<dependencies>
    <dependency>
        <groupId>org.hibernate</groupId>
        <artifactId>query-validator</artifactId>
        <version>1.0-SNAPSHOT</version>
        <optional>true</optional>
    </dependency>
<dependencies>

**Comment by gavinking** [comment]
Hi, just build it from source, there are instructions in the README.
